// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialStats():Promise<main.DashboardData>;

export function SyncHistory():Promise<main.SyncResult>;
