// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialStats():Promise<main.DashboardData>;

export function GetWishHistory(arg1:number,arg2:number):Promise<Array<main.WishRecord>>;

export function SyncHistory():Promise<main.SyncResult>;
