// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportWishes(arg1, arg2) {
  return window['go']['main']['App']['ExportWishes'](arg1, arg2);
}

export function SyncHistory() {
  return window['go']['main']['App']['SyncHistory']();
}
